import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Switch } from "@/components/ui/switch";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowDownRight, ArrowUpRight, Database, EyeOff, LockKeyhole, Medal, RefreshCw, ShieldCheck, Sparkles, Target, TrendingUp, Trophy } from "lucide-react";
import { useEffect, useState } from "react";

type PublishedAnalysis = { title: string; summary: string; sections: { heading: string; body: string }[] };

function MetricCard({ label, value, detail, accent = "cyan", icon: Icon }: { label: string; value: string; detail: string; accent?: "cyan" | "pink" | "lime"; icon: typeof Trophy }) {
  const color = accent === "pink" ? "text-pink-300" : accent === "lime" ? "text-lime-300" : "text-cyan-300";
  const bg = accent === "pink" ? "bg-pink-400/10" : accent === "lime" ? "bg-lime-300/10" : "bg-cyan-300/10";
  return <div className="hud-card p-5"><div className="flex items-center justify-between"><span className={`grid h-9 w-9 place-items-center rounded-lg ${bg}`}><Icon className={`h-4 w-4 ${color}`} /></span><span className="eyebrow text-slate-500">Private view</span></div><p className="mt-5 text-xs uppercase tracking-[0.2em] text-slate-500">{label}</p><p className={`metric-number mt-1 ${color}`}>{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div>;
}

export default function StudentDashboard() {
  const { user } = useAuth();
  const academic = trpc.academic.me.useQuery(undefined, { enabled: Boolean(user), retry: false });
  const subjectAnalytics = trpc.academic.subjectAnalytics.useQuery({ cohortId: academic.data?.student?.cohortId ?? 0, semesterId: academic.data?.student?.currentSemesterId ?? 0 }, { enabled: Boolean(academic.data?.student?.cohortId && academic.data?.student?.currentSemesterId), retry: false });
  const academicRankings = trpc.academic.rankings.useQuery({ cohortId: academic.data?.student?.cohortId ?? 0, semesterId: academic.data?.student?.currentSemesterId ?? 0, rankingType: "ACADEMIC" }, { enabled: Boolean(academic.data?.student?.cohortId && academic.data?.student?.currentSemesterId), retry: false });
  const fantasyRankings = trpc.academic.rankings.useQuery({ cohortId: academic.data?.student?.cohortId ?? 0, semesterId: academic.data?.student?.currentSemesterId ?? 0, rankingType: "FANTASY" }, { enabled: Boolean(academic.data?.student?.cohortId && academic.data?.student?.currentSemesterId), retry: false });
  const privacy = trpc.privacy.get.useQuery(undefined, { enabled: Boolean(user), retry: false });
  const utils = trpc.useUtils();
  const updatePrivacy = trpc.privacy.update.useMutation({ onSuccess: async () => { await utils.privacy.get.invalidate(); toast.success("Visibility protocol updated"); }, onError: error => toast.error(error.message) });
  const [privateMode, setPrivateMode] = useState(false);

  useEffect(() => {
    if (privacy.data) setPrivateMode(privacy.data.privateMode);
  }, [privacy.data]);

  if (academic.isLoading) return <div className="grid min-h-[70vh] place-items-center"><RefreshCw className="h-6 w-6 animate-spin text-cyan-300" /></div>;
  if (academic.error) return <div className="hud-card mx-auto mt-10 max-w-xl p-8 text-center"><LockKeyhole className="mx-auto h-9 w-9 text-pink-300" /><h1 className="mt-5 display-font text-xl font-bold">Verified access required</h1><p className="mt-3 text-sm leading-6 text-slate-400">Your account is authenticated, but no verified student record is linked yet. Academic data remains protected until an administrator completes verification.</p><Badge className="mt-5 border-pink-300/30 bg-pink-300/10 text-pink-200">{academic.error.data?.code ?? "ACCESS CONTROL"}</Badge></div>;

  if (academic.data?.role === "ADMIN") return <div className="mx-auto mt-12 max-w-xl hud-card p-9 text-center"><ShieldCheck className="mx-auto h-9 w-9 text-cyan-300" /><h1 className="mt-5 display-font text-xl font-bold">Admin session detected</h1><p className="mt-3 text-sm leading-6 text-slate-400">This route is reserved for student performance views. Use the admin workspace to manage imports, scoring, publishing, and audit history.</p><Button className="mt-6 bg-cyan-300 text-slate-950 hover:bg-cyan-200" onClick={() => window.location.assign("/admin")}>Open admin workspace</Button></div>;

  const student = academic.data?.student;
  const publishedResults = academic.data?.results ?? [];
  const numericScores = publishedResults.map(item => Number(item.result.normalizedScore ?? item.result.percentage)).filter(score => Number.isFinite(score));
  const averageScore = numericScores.length ? numericScores.reduce((total, score) => total + score, 0) / numericScores.length : null;
  const scoreLabel = averageScore === null ? "—" : averageScore.toFixed(1);
  const semesterTrend = Array.from(new Map(publishedResults.map(item => [item.semester.id, { label: `S${String(item.semester.number).padStart(2, "0")}`, scores: publishedResults.filter(candidate => candidate.semester.id === item.semester.id).map(candidate => Number(candidate.result.normalizedScore ?? candidate.result.percentage)).filter(score => Number.isFinite(score)) }])).values()).map(item => ({ ...item, average: item.scores.length ? item.scores.reduce((sum, score) => sum + score, 0) / item.scores.length : 0 }));
  const recentScores = numericScores.slice(-4);
  const recentForm = recentScores.length ? recentScores.reduce((sum, score) => sum + score, 0) / recentScores.length : null;
  const firstAttemptSuccess = publishedResults.length ? (publishedResults.filter(item => item.result.normalizedResult === "PASS" || Number(item.result.normalizedScore ?? item.result.percentage) >= 60).length / publishedResults.length) * 100 : null;
  const trendMax = Math.max(...semesterTrend.map(item => item.average), 100);
  const academicRank = academicRankings.data?.find(row => row.studentId === student?.id);
  const fantasyRank = fantasyRankings.data?.find(row => row.studentId === student?.id);
  return <div className="mx-auto max-w-7xl space-y-7">
    <header className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">Student command center / secure session</p><h1 className="mt-2 display-font text-3xl font-black tracking-tight sm:text-4xl">Good to see you, <span className="neon-cyan">{student?.fullName?.split(" ")[0] ?? "operator"}.</span></h1><p className="mt-2 text-sm text-slate-500">Your academic signal is visible only within the configured policy boundary.</p></div><div className="flex items-center gap-3"><Badge variant="outline" className="border-cyan-300/30 bg-cyan-300/10 px-3 py-1.5 text-cyan-200"><ShieldCheck className="mr-2 h-3.5 w-3.5" /> Verified profile</Badge><Button variant="outline" className="border-white/10 bg-white/[.03] text-slate-300 hover:bg-white/[.07]" onClick={() => toast.info("Data refresh is available after the next published semester snapshot.")}><RefreshCw className="mr-2 h-4 w-4" />Refresh</Button></div></header>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Overall rating" value={scoreLabel} detail={publishedResults.length ? `${publishedResults.length} published results` : "Awaiting published results"} icon={Target} /><MetricCard label="Academic rank" value={academicRank ? `#${academicRank.rank}` : "—"} detail={academicRank?.previousRank ? `${academicRank.previousRank > academicRank.rank ? "↑" : "↓"} from #${academicRank.previousRank}` : "Published snapshot required"} accent="pink" icon={Trophy} /><MetricCard label="Fantasy score" value={fantasyRank ? Number(fantasyRank.score).toFixed(1) : "—"} detail={fantasyRank ? `Fantasy rank #${fantasyRank.rank}` : "Versioned formula required"} accent="lime" icon={Sparkles} /><MetricCard label="Momentum" value={semesterTrend.length > 1 ? `${(semesterTrend.at(-1)!.average - semesterTrend[0]!.average >= 0 ? "+" : "")}${(semesterTrend.at(-1)!.average - semesterTrend[0]!.average).toFixed(1)}` : "—"} detail="Change across published semesters" icon={TrendingUp} /></div>
    <div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]">
      <Card className="hud-card border-0 bg-card/70"><CardHeader className="flex-row items-start justify-between"><div><p className="eyebrow">Performance telemetry</p><CardTitle className="mt-2 display-font text-xl">Semester trend</CardTitle></div><Badge variant="outline" className="border-white/10 text-slate-500">S01—S06</Badge></CardHeader><CardContent><div className="relative mt-2 h-56 overflow-hidden rounded-xl border border-white/5 bg-black/20"><div className="absolute inset-0 bg-[linear-gradient(rgba(105,241,255,.08)_1px,transparent_1px),linear-gradient(90deg,rgba(105,241,255,.08)_1px,transparent_1px)] bg-[size:40px_40px]" /><div className="absolute inset-x-8 top-1/2 h-px bg-white/10" /><div className="absolute inset-y-7 left-8 border-l border-white/10" />{semesterTrend.length ? <div className="absolute inset-x-8 inset-y-7 flex items-end gap-3">{semesterTrend.map(item => <div key={item.label} className="flex min-w-0 flex-1 flex-col items-center gap-2"><div className="w-full rounded-t-md bg-cyan-300/70 shadow-[0_0_18px_rgba(105,241,255,.28)]" style={{ height: `${Math.max((item.average / trendMax) * 100, 5)}%` }} /><span className="text-[10px] uppercase tracking-[.16em] text-slate-600">{item.label}</span></div>)}</div> : <div className="absolute inset-0 grid place-items-center text-center"><Activity className="mx-auto h-7 w-7 text-slate-600" /><p className="mt-3 text-sm font-medium text-slate-400">No published semester data yet</p><p className="mt-1 text-xs text-slate-600">Trend visualization activates after admin publication.</p></div>}<div className="absolute bottom-3 left-8 right-8 flex justify-between text-[10px] uppercase tracking-[.18em] text-slate-600"><span>Semester 01</span><span>Semester 03</span><span>Semester 06</span></div></div></CardContent></Card>
      <Card className="hud-card border-0 bg-card/70"><CardHeader><p className="eyebrow">Recent form</p><CardTitle className="mt-2 display-font text-xl">Signal breakdown</CardTitle></CardHeader><CardContent className="space-y-3">{[{label:"Consistency", value: recentScores.length ? `${Math.max(0, 100 - (Math.max(...recentScores) - Math.min(...recentScores))).toFixed(0)}%` : "—", icon: RefreshCw},{label:"First-attempt success", value: firstAttemptSuccess === null ? "—" : `${firstAttemptSuccess.toFixed(0)}%`, icon: ArrowUpRight},{label:"Improvement", value: semesterTrend.length > 1 ? `${(semesterTrend.at(-1)!.average - semesterTrend[0]!.average >= 0 ? "+" : "")}${(semesterTrend.at(-1)!.average - semesterTrend[0]!.average).toFixed(1)}` : "—", icon: TrendingUp},{label:"Recent form", value: recentForm === null ? "—" : recentForm.toFixed(1), icon: Medal}].map(({label, value, icon: Icon}) => <div key={label} className="flex items-center justify-between rounded-xl border border-white/5 bg-white/[.025] p-3"><span className="flex items-center gap-3 text-sm text-slate-400"><Icon className="h-4 w-4 text-cyan-300" />{label}</span><span className="display-font text-sm text-cyan-200">{value}</span></div>)}<div className="mt-5 rounded-xl border border-pink-300/15 bg-pink-300/[.05] p-4"><p className="eyebrow text-pink-200">Rule-based achievements</p>{academic.data?.achievements?.length ? <div className="mt-3 flex flex-wrap gap-2">{academic.data.achievements.map(item => <Badge key={item.award.id} variant="outline" className="border-pink-300/25 text-pink-200"><Medal className="mr-1.5 h-3.5 w-3.5" />{item.achievement.name}</Badge>)}</div> : <p className="mt-2 text-sm text-slate-400">No achievements awarded yet. Badges appear only after a deterministic, auditable rule is satisfied.</p>}</div></CardContent></Card>
    </div>
    <div className="grid gap-5 lg:grid-cols-[1fr_.8fr]">
      <Card className="hud-card border-0 bg-card/70"><CardHeader><p className="eyebrow">Leaderboard access</p><CardTitle className="mt-2 display-font text-xl">Your cohort position</CardTitle></CardHeader><CardContent>{academicRankings.data?.length ? <div className="space-y-2">{academicRankings.data.slice(0, 8).map(row => <div key={row.id} className={`flex items-center justify-between rounded-xl border p-3 ${row.studentId === student?.id ? "border-cyan-300/30 bg-cyan-300/[.07]" : "border-white/5 bg-white/[.025]"}`}><span className="flex items-center gap-3"><span className="display-font text-xs text-slate-500">#{String(row.rank).padStart(2, "0")}</span><span className="text-sm text-slate-300">{row.studentId === student?.id ? "You" : "Student signal"}</span></span><span className="text-sm font-semibold text-cyan-200">{Number(row.score).toFixed(1)}</span></div>)}</div> : subjectAnalytics.data?.length ? <div className="space-y-3">{subjectAnalytics.data.slice(0, 5).map(item => <div key={item.subjectId} className="rounded-xl border border-white/5 bg-white/[.025] p-3"><div className="flex items-center justify-between gap-3"><span className="text-sm font-medium text-slate-300">{item.name}</span><span className="text-xs text-cyan-200">{item.averageScore.toFixed(1)}</span></div><div className="mt-2 flex items-center justify-between text-[10px] uppercase tracking-[.16em] text-slate-600"><span>{item.code}</span><span>{item.passRate}% pass rate</span></div></div>)}</div> : <div className="rounded-xl border border-dashed border-white/10 p-8 text-center"><Trophy className="mx-auto h-8 w-8 text-slate-600" /><p className="mt-3 text-sm text-slate-400">Subject analytics remain empty until results are published.</p><p className="mt-1 text-xs text-slate-600">Private-mode rules are applied server-side before cohort aggregates are returned.</p></div>}</CardContent></Card>
      <Card className="hud-card border-0 bg-card/70"><CardHeader><p className="eyebrow">Visibility protocol</p><CardTitle className="mt-2 display-font text-xl">Control your exposure</CardTitle></CardHeader><CardContent><div className="flex items-start justify-between gap-4 rounded-xl border border-pink-300/15 bg-pink-300/[.04] p-4"><div><div className="flex items-center gap-2"><EyeOff className="h-4 w-4 text-pink-300" /><p className="text-sm font-semibold text-slate-200">Private Mode</p></div><p className="mt-2 text-xs leading-5 text-slate-500">Hide your profile, rank, and subject statistics from other students. You can always see your own data.</p></div><Switch checked={privateMode} disabled={updatePrivacy.isPending || privacy.isLoading} onCheckedChange={checked => { setPrivateMode(checked); updatePrivacy.mutate({ privateMode: checked, showProfile: !checked, showRank: !checked, showSubjectStats: !checked }); }} /></div><div className="mt-4 flex items-center gap-2 text-xs text-slate-600"><LockKeyhole className="h-3.5 w-3.5 text-cyan-300" />Visibility decisions are logged for accountability.</div></CardContent></Card>
    </div>
    <Card className="hud-card border-0 bg-card/70"><CardHeader className="flex-row items-start justify-between"><div><p className="eyebrow">Published result ledger</p><CardTitle className="mt-2 display-font text-xl">Your official results</CardTitle></div><Badge variant="outline" className="border-white/10 text-slate-500">Read-only</Badge></CardHeader><CardContent>{publishedResults.length ? <div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead className="border-b border-white/10 text-[10px] uppercase tracking-[.18em] text-slate-600"><tr><th className="pb-3">Semester</th><th className="pb-3">Subject</th><th className="pb-3">Result</th><th className="pb-3 text-right">Score</th></tr></thead><tbody className="divide-y divide-white/5">{publishedResults.map(item => <tr key={item.result.id} className="text-slate-300"><td className="py-3 text-slate-500">S{String(item.semester.number).padStart(2, "0")}</td><td className="py-3"><span className="font-medium">{item.subject.name}</span><span className="ml-2 text-xs text-slate-600">{item.subject.code}</span></td><td className="py-3"><Badge variant="outline" className="border-cyan-300/20 bg-cyan-300/[.05] text-cyan-200">{item.result.normalizedResult ?? "PENDING"}</Badge></td><td className="py-3 text-right font-semibold text-cyan-200">{item.result.normalizedScore ?? item.result.percentage ?? "—"}</td></tr>)}</tbody></table></div> : <div className="rounded-xl border border-dashed border-white/10 p-8 text-center"><Database className="mx-auto h-7 w-7 text-slate-600" /><p className="mt-3 text-sm text-slate-400">No published result rows yet.</p><p className="mt-1 text-xs text-slate-600">This ledger stays empty until an admin confirms and publishes a validated import.</p></div>}</CardContent></Card>
    {academic.data?.analyses?.length ? <Card className="hud-card border-0 bg-card/70"><CardHeader><p className="eyebrow">Published coach notes</p><CardTitle className="mt-2 display-font text-xl">Your semester analysis</CardTitle></CardHeader><CardContent className="space-y-4">{academic.data.analyses.map(analysis => { let payload: PublishedAnalysis | null = null; try { payload = JSON.parse(analysis.payload) as PublishedAnalysis; } catch { payload = null; } return payload ? <div key={analysis.id} className="rounded-xl border border-violet-300/15 bg-violet-300/[.04] p-5"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow text-violet-200">Published signal</p><h3 className="mt-2 display-font text-lg text-slate-100">{payload.title}</h3></div><Sparkles className="h-5 w-5 text-violet-300" /></div><p className="mt-3 text-sm leading-6 text-slate-400">{payload.summary}</p><div className="mt-4 grid gap-3 md:grid-cols-2">{payload.sections.map(section => <div key={section.heading} className="rounded-lg border border-white/5 bg-black/20 p-4"><p className="text-sm font-semibold text-violet-200">{section.heading}</p><p className="mt-2 text-sm leading-6 text-slate-400">{section.body}</p></div>)}</div></div> : null; })}</CardContent></Card> : null}
  </div>;
}
