import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { LockKeyhole, ShieldCheck } from "lucide-react";

export default function StudentProfile() {
  const academic = trpc.academic.me.useQuery(undefined, { retry: false });
  if (academic.isLoading) return <div className="grid min-h-[60vh] place-items-center text-cyan-300">Loading secure profile…</div>;
  if (academic.error || academic.data?.role !== "STUDENT" || !academic.data.student) return <div className="hud-card mx-auto mt-12 max-w-xl p-9 text-center"><LockKeyhole className="mx-auto h-9 w-9 text-pink-300" /><h1 className="mt-5 display-font text-xl font-bold">Profile access is protected</h1><p className="mt-3 text-sm leading-6 text-slate-400">Only a verified student can view this profile route. No academic record is returned for an unverified or administrative session.</p></div>;
  const { student, privacy } = academic.data;
  return <div className="mx-auto max-w-4xl space-y-6"><header><p className="eyebrow">Identity layer / self view</p><h1 className="mt-2 display-font text-3xl font-black">Your <span className="neon-cyan">profile signal.</span></h1><p className="mt-2 text-sm text-slate-500">This view is self-only and backed by the authenticated student session.</p></header><div className="grid gap-5 md:grid-cols-[1.1fr_.9fr]"><Card className="hud-card border-0 bg-card/70"><CardHeader><Badge className="w-fit border-cyan-300/20 bg-cyan-300/10 text-cyan-200"><ShieldCheck className="mr-2 h-3.5 w-3.5" />Verified record</Badge><CardTitle className="mt-4 display-font text-2xl">{student.fullName}</CardTitle></CardHeader><CardContent className="grid gap-4 text-sm"><div><p className="eyebrow">Student identifier</p><p className="mt-1 text-slate-300">{student.studentId}</p></div><div><p className="eyebrow">Status</p><p className="mt-1 text-slate-300">{student.status}</p></div></CardContent></Card><Card className="hud-card border-0 bg-card/70"><CardHeader><p className="eyebrow">Privacy protocol</p><CardTitle className="mt-2 display-font text-xl">Visibility state</CardTitle></CardHeader><CardContent className="space-y-3 text-sm">{[["Private mode", privacy?.privateMode], ["Profile visible", privacy?.showProfile], ["Rank visible", privacy?.showRank], ["Subject stats visible", privacy?.showSubjectStats]].map(([label, value]) => <div key={String(label)} className="flex items-center justify-between rounded-lg border border-white/5 bg-white/[.025] p-3"><span className="text-slate-400">{label}</span><span className={value ? "text-cyan-200" : "text-pink-200"}>{value ? "ON" : "OFF"}</span></div>)}</CardContent></Card></div></div>;
}
